#ifndef LEDHARDWARE_H_INCLUDED
#define LEDHARDWARE_H_INCLUDED

/* LED auf Basisplatine */
#define LEDROT_PORT PORTA
#define LEDROT_PIN  PIN4_bm

#define LEDROTSETUP LEDROT_PORT.DIRSET=LEDROT_PIN
#define LEDROT_ON   LEDROT_PORT.OUTCLR=LEDROT_PIN
#define LEDROT_OFF  LEDROT_PORT.OUTSET=LEDROT_PIN
#define LEDROT_TOGGLE  LEDROT_PORT.OUTTGL=LEDROT_PIN


#endif // LEDHARDWARE_H_INCLUDED
